# -*- coding: utf-8 -*-
"""Object_Detection_exam_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12LUuH1reVFLD6kzdHx-WI4Ebk7ig7Cae
"""

path=r'C:\Users\Anjali\Downloads\Persian_Car_Plates_YOLOV8'

from ultralytics import YOLO

model = YOLO('yolov8n.pt')


model.train(data=r'C:\Users\Anjali\Downloads\Persian_Car_Plates_YOLOV8\data.yaml', epochs=10, amp=False)

from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt


model = YOLO(r'C:\Users\Anjali\Downloads\runs\detect\train\weights\best.pt')
img_path = r'C:\Users\Anjali\Downloads\Persian_Car_Plates_YOLOV8\valid\images\490_png.rf.2959ca57f51e65d7302ef87dd5d81e7d.jpg'
image = cv2.imread(img_path)

results = model.predict(source=img_path, save=True, conf=0.35)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()

import matplotlib.pyplot as plt
import cv2
path =  r'C:\Users\Anjali\Downloads\runs\detect\predict\490_png.rf.2959ca57f51e65d7302ef87dd5d81e7d.jpg'
image = cv2.imread(path)
plt.imshow(image)

